### ISSUE TITLE
Delete this code

### ISSUE THREAD

**Issue by ndsrf** [GeorgianaSchipor/TestRepository#1]
Hi

Would it be possible for you to delete this code? It is an exercise provided by Sequel and we would like to not have solutions available on the internet. 

Thanks.

**Comment by georgianasch** [comment]
Hello,

Sure,  no problem.

Have a nice day,
Georgiana



În lun., 25 iun. 2018 la 13:09, Javier García Magna <
notifications@github.com> a scris:
